### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by expez** [PythonNut/company-flx#7] opened 2015-10-20 08:36 UTC
Hi I installed this yesterday and took it for a spin. 

 I'm working on a toptal craptop and noticed that completions in elisp areannoyingly slow.  I figured I'd let you know that you might want to document `company-flx-limit` in the readme to help people like me out.

As I tried to update the `company-flx-limit` I only got as far as `(setq company-flx-` before emacs froze completely with 100% cpu usage.  I couldn't even get out of this using <kbd>C-g</kbd>.  I've no idea what happened, but it sure was annoying :p  After restarting and putting the limit at 250, everything is a bit smoother.

While working on some clojure code, yesterday, I also noticed that I'd get no completions at all, under some circumstances.  This happened for a good while when working in the REPL, but then later it started working.

This is more of an FYI. Except for the suggestions about extending the README there isn't really anything actionable in here, so just close this unless you recognize any of this from your own usage and want to investigate further.

**Comment by PythonNut** [comment] 2015-10-20 14:54
Hi. 

README should be covered now.

> While working on some clojure code, yesterday, I also noticed that I'd get no completions at all, under some circumstances. This happened for a good while when working in the REPL, but then later it started working.

If you can reproduce this (preferably without `clojure`, since I don't have any experience with that language) that would be great.

I'm going to close this. Please do report back if you find out what the cause was, and I'll reopen it.

**Closed as completed by PythonNut** 2015-10-20 14:54 UTC
