### ISSUE TITLE
Wrong type argument: hash-table-p, "Stores company-mode's flx-cache"

### ISSUE THREAD

**Issue by tuhdo** [PythonNut/company-flx#5] opened 2015-10-19 02:44 UTC
Step to reproduce:
- Enable `company-flx-mode`.
- Try `company-complete`.

Stack trace: 

![company-flx-trace](https://cloud.githubusercontent.com/assets/4818719/10568684/e757611c-7645-11e5-8ea6-dee11a8f84e2.jpg)

**Comment by PythonNut** [comment] 2015-10-19 02:49
Duplicate of #4. Sorry about the mishap with the cache initialization.

MELPA should rebuild it soon, **fingers crossed**.

**Closed as completed by PythonNut** 2015-10-19 02:49 UTC
